apiVersion: v1
kind: Pod
metadata:
  name: debug-runner
  namespace: arc-systems
spec:
  serviceAccountName: kubeflow-oracle-vm-gpu-a10-1-gha-rs-no-permission
  containers:
  - name: runner
    image: akashjaiswal03/kubeflow-gpu-cloudrunner-oci:latest
    imagePullPolicy: Always
    command: ["/bin/sh", "-c", "sleep 3600"]
    env:
    - name: OCI_CONFIG_FILE
      value: /etc/oci/config
    volumeMounts:
    - mountPath: /etc/oci
      name: oci-config
      readOnly: true
    - mountPath: /oci
      name: oci-api-key
      readOnly: true
  volumes:
  - name: oci-config
    secret:
      secretName: oci-config
  - name: oci-api-key
    secret:
      secretName: oci-api-key
