---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: my-oracle-vm-gpu-a10-1-gha-rs-no-permission
  namespace: arc-systems
  labels:
    helm.sh/chart: gha-rs-0.11.0
    app.kubernetes.io/name: my-oracle-vm-gpu-a10-1
    app.kubernetes.io/instance: my-oracle-vm-gpu-a10-1
    app.kubernetes.io/version: "0.11.0"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: gha-rs
    actions.github.com/scale-set-name: my-oracle-vm-gpu-a10-1
    actions.github.com/scale-set-namespace: arc-systems
  finalizers:
    - actions.github.com/cleanup-protection
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: my-oracle-vm-gpu-a10-1-gha-rs-manager
  namespace: arc-systems
  labels:
    helm.sh/chart: gha-rs-0.11.0
    app.kubernetes.io/name: my-oracle-vm-gpu-a10-1
    app.kubernetes.io/instance: my-oracle-vm-gpu-a10-1
    app.kubernetes.io/version: "0.11.0"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: gha-rs
    actions.github.com/scale-set-name: my-oracle-vm-gpu-a10-1
    actions.github.com/scale-set-namespace: arc-systems
    app.kubernetes.io/component: manager-role
  finalizers:
    - actions.github.com/cleanup-protection
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - create
  - delete
  - get
- apiGroups:
  - ""
  resources:
  - pods/status
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  verbs:
  - create
  - delete
  - get
  - patch
  - update
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - roles
  verbs:
  - create
  - delete
  - get
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: my-oracle-vm-gpu-a10-1-gha-rs-manager
  namespace: arc-systems
  labels:
    helm.sh/chart: gha-rs-0.11.0
    app.kubernetes.io/name: my-oracle-vm-gpu-a10-1
    app.kubernetes.io/instance: my-oracle-vm-gpu-a10-1
    app.kubernetes.io/version: "0.11.0"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: gha-rs
    actions.github.com/scale-set-name: my-oracle-vm-gpu-a10-1
    actions.github.com/scale-set-namespace: arc-systems
    app.kubernetes.io/component: manager-role-binding
  finalizers:
    - actions.github.com/cleanup-protection
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: my-oracle-vm-gpu-a10-1-gha-rs-manager
subjects:
- kind: ServiceAccount
  name: 
    cncf-gha-controller-gha-rs-controller
  namespace: 
    arc-systems
---
apiVersion: actions.github.com/v1alpha1
kind: AutoscalingRunnerSet
metadata:
  name: my-oracle-vm-gpu-a10-1
  namespace: arc-systems
  labels:
    app.kubernetes.io/component: "autoscaling-runner-set"
    helm.sh/chart: gha-rs-0.11.0
    app.kubernetes.io/name: my-oracle-vm-gpu-a10-1
    app.kubernetes.io/instance: my-oracle-vm-gpu-a10-1
    app.kubernetes.io/version: "0.11.0"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: gha-rs
    actions.github.com/scale-set-name: my-oracle-vm-gpu-a10-1
    actions.github.com/scale-set-namespace: arc-systems
  annotations:
    actions.github.com/values-hash: 5a160ea308cd51d6f4c27515e5040d9dc34be0acda7289ea0d7ad9cffff39e1
    actions.github.com/cleanup-manager-role-binding: my-oracle-vm-gpu-a10-1-gha-rs-manager
    actions.github.com/cleanup-manager-role-name: my-oracle-vm-gpu-a10-1-gha-rs-manager
    actions.github.com/cleanup-no-permission-service-account-name: my-oracle-vm-gpu-a10-1-gha-rs-no-permission
spec:
  githubConfigUrl: https://github.com/enterprises/cncf
  githubConfigSecret: github-arc-secret
  maxRunners: 100
  minRunners: 0
  template:
    spec:
      containers:
      - name: runner
        image: akashjaiswal03/my-cloudrunner-oci:latest
        args:
        - --arch=amd64
        - --shape=VM.GPU.A10.1
        - --shape-ocpus=15
        - --shape-memory-in-gbs=240
        - --availability-domain=YOUR_AVAILABILITY_DOMAIN
        - --compartment-id=YOUR_COMPARTMENT_ID
        - --subnet-id=YOUR_SUBNET_ID
        env:
        - name: OCI_CONFIG_FILE
          value: /etc/oci/config
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - mountPath: /etc/oci
          name: oci-config
          readOnly: true
        - mountPath: /oci
          name: oci-api-key
          readOnly: true
      restartPolicy: Never
      securityContext:
        fsGroup: 1001
        supplementalGroups:
        - 999
      serviceAccountName: my-oracle-vm-gpu-a10-1-gha-rs-no-permission
      volumes:
      - name: oci-config
        secret:
          secretName: oci-config
      - name: oci-api-key
        secret:
          secretName: oci-api-key
